### ISSUE TITLE
Questions about a symbol in the paper

### ISSUE THREAD

**Issue by wangtsiao** [DAHeath/one-hot-garbling#1]
Hi, you really did a nice job! 

I found a place to difficult to understand when I read your paper.

In 3.2, what's mean <img src="http://chart.googleapis.com/chart?cht=tx&chl=a \triangle" style="border:none;"> . Considering <img src="http://chart.googleapis.com/chart?cht=tx&chl=a" style="border:none;">  is a bit and <img src="http://chart.googleapis.com/chart?cht=tx&chl=\triangle" style="border:none;"> is a string, what's the operational relationship between <img src="http://chart.googleapis.com/chart?cht=tx&chl=a" style="border:none;">  and <img src="http://chart.googleapis.com/chart?cht=tx&chl=\triangle" style="border:none;"> ?

<img width="179" alt="截屏2022-03-02 10 41 44" src="https://user-images.githubusercontent.com/70847926/156284630-52568f73-b12c-4e5d-83ca-afdf99e0f354.png">

**Comment by DAHeath** [comment]
Hi! You can think of  `Delta` as a vector of bits. Then `a Delta` is simply `Delta` scaled by the bit `a`. So if `a = 0`, then `a Delta` is the all-zero string. If `a = 1`, then `a Delta = Delta`.
